[workspace]
members = [
  "project_generator",
  "year_2022/*",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1"
bitvec = "1"
criterion = "0.5"
nom = "7.1"
rayon = "1.8"
regex = "1.10"
rustc-hash = "1.1"
