[workspace]
members = ["year_2022/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.70"
criterion = "0.4"
nom = "7.1.3"
rayon = "1.7.0"
rustc-hash = "1.1.0"
